# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_in',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_out',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='item',
            name='total_stock',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
    ]
